### ISSUE TITLE
I love the UI design and Color style, is there a name for it ?

### ISSUE THREAD

**Issue by syunhan** [Mohamed-code-13/To-Do-App-Flutter#1]
Thanks for your working and sharing this app. I`m very love this UI / Color design style, i feel it a little similar like https://alpinejs.dev/ frontpage.
Does this design style has a name ?

**Comment by Mohamed-code-13** [comment]
Hi @syunhan ,

Thank you for the positive feedback! I'm delighted you liked the UI design and color style. 

There is no specific design style that I used to build this project. I searched for similar designs and tried to create my own one. It's great to hear that you find it similar to the design style of the Alpine.js website.

I used this color for the main color theme: #08c4b2. I also used a Google font called Roboto Mono.

I hope I've helped you and I'm glad you're enjoying my work!

Best regards,
@Mohamed-code-13

**Comment by syunhan** [comment]
@Mohamed-code-13 thanks for your patient reply  : )
